export const GET_LINES = 'GET_LINES';
export const GET_LINES_ERROR = 'GET_LINES_ERROR';
export const GET_LINES_SUCCESS = 'GET_LINES_SUCCESS';

export const GET_LINEJOBS = 'GET_LINEJOBS';
export const GET_LINEJOBS_ERROR = 'GET_LINEJOBS_ERROR';
export const GET_LINEJOBS_SUCCESS = 'GET_LINEJOBS_SUCCESS';

export const GET_QP = 'GET_QP';
export const GET_QP_ERROR = 'GET_QP_ERROR';
export const GET_QP_SUCCESS = 'GET_QP_SUCCESS';

export const GET_LINEJOB_STATUSES = 'GET_LINEJOB_STATUSES';
export const GET_LINEJOB_STATUSES_ERROR = 'GET_LINEJOB_STATUSES_ERROR';
export const GET_LINEJOB_STATUSES_SUCCESS = 'GET_LINEJOB_STATUSES_SUCCESS';

export const GET_LINEJOB_DETAILS = 'GET_LINEJOB_DETAILS';
export const GET_LINEJOB_DETAILS_SUCCESS = 'GET_LINEJOB_DETAILS_SUCCESS';
export const GET_LINEJOB_DETAILS_ERROR = 'GET_LINEJOB_DETAILS_ERROR';

export const GET_LINEJOB_DRAWINGS = 'GET_LINEJOB_DRAWINGS';
export const GET_LINEJOB_DRAWINGS_SUCCESS = 'GET_LINEJOB_DRAWINGS_SUCCESS';
export const GET_LINEJOB_DRAWINGS_ERROR = 'GET_LINEJOB_DRAWINGS_ERROR';

export const UPDATE_LINEJOB_DETAILS = 'UPDATE_LINEJOB_DETAILS';
export const UPDATE_LINEJOB_DETAILS_SUCCESS = 'UPDATE_LINEJOB_DETAILS_SUCCESS';
export const UPDATE_LINEJOB_DETAILS_ERROR = 'UPDATE_LINEJOB_DETAILS_ERROR';

export const UPDATE_LINEJOB_STATUS = 'UPDATE_LINEJOB_STATUS';
export const UPDATE_LINEJOB_STATUS_SUCCESS = 'UPDATE_LINEJOB_STATUS_SUCCESS';
export const UPDATE_LINEJOB_STATUS_ERROR = 'UPDATE_LINEJOB_STATUS_ERROR';

export const UPDATE_LINEJOB_QUEUE = 'UPDATE_LINEJOB_QUEUE';
export const UPDATE_LINEJOB_QUEUE_SUCCESS = 'UPDATE_LINEJOB_QUEUE_SUCCESS';
export const UPDATE_LINEJOB_QUEUE_ERROR = 'UPDATE_LINEJOB_QUEUE_ERROR';

export const GET_LINEJOB_DOCUMENTS = 'GET_LINEJOB_DOCUMENTS';
export const GET_LINEJOB_DOCUMENTS_SUCCESS = 'GET_LINEJOB_DOCUMENTS_SUCCESS';
export const GET_LINEJOB_DOCUMENTS_ERROR = 'GET_LINEJOB_DOCUMENTS_ERROR';

export const HANDLE_UNSAVED_CHANGES = 'HANDLE_UNSAVED_CHANGES';
export const HANDLE_UNSAVED_CHANGES_IN_DOCUMENTS = 'HANDLE_UNSAVED_CHANGES_IN_DOCUMENTS';
export const HANDLE_UNSAVED_CHANGES_IN_DRAWINGS = 'HANDLE_UNSAVED_CHANGES_IN_DRAWINGS';
export const HANDLE_UNSAVED_CHANGES_IN_BOM = 'HANDLE_UNSAVED_CHANGES_IN_BOM';
export const HANDLE_UNSAVED_CHANGES_IN_NOTES = 'HANDLE_UNSAVED_CHANGES_IN_NOTES';
export const HANDLE_UNSAVED_CHANGES_IN_ANNOTATIONS = 'HANDLE_UNSAVED_CHANGES_IN_ANNOTATIONS';
export const HANDLE_UNSAVED_CHANGES_IN_ITPS = 'HANDLE_UNSAVED_CHANGES_IN_ITPS';

export const UPLOAD_NEW_LINEJOB_DOCUMENTS = 'UPLOAD_NEW_LINEJOB_DOCUMENTS';
export const UPDATE_SAVED_LINEJOB_DOCUMENTS = 'UPDATE_SAVED_LINEJOB_DOCUMENTS';
export const UPDATE_LINEJOB_DRAWINGS = 'UPDATE_LINEJOB_DRAWINGS';
export const UPDATE_SAVED_LINEJOB_DRAWINGS = 'UPDATE_SAVED_LINEJOB_DRAWINGS';

export const GET_LINEJOB_BOMS = 'GET_LINEJOB_BOMS';
export const GET_LINEJOB_BOMS_SUCCESS = 'GET_LINEJOB_BOMS_SUCCESS';
export const GET_LINEJOB_BOMS_ERROR = 'GET_LINEJOB_BOMS_ERROR';
export const UPDATE_BOMS = 'UPDATE_BOMS';
export const LIVE_UPDATE_BOMS = 'LIVE_UPDATE_BOMS';

export const CLEAR_JOB_DETAILS_DATA = 'CLEAR_JOB_DETAILS_DATA';
export const RESET_UPLOADED_FILES_DATA = 'RESET_UPLOADED_FILES_DATA';
export const UPDATE_LINEJOB_NOTES = 'UPDATE_LINEJOB_NOTES';
export const CLEAR_LINEJOB_NOTES = 'CLEAR_LINEJOB_NOTES';

export const GET_LINEJOB_NOTES = 'GET_LINEJOB_NOTES';
export const GET_LINEJOB_NOTES_SUCCESS = 'GET_LINEJOB_NOTES_SUCCESS';
export const GET_LINEJOB_NOTES_ERROR = 'GET_LINEJOB_NOTES_ERROR';

export const CREATE_LINEJOB = 'CREATE_LINEJOB';
export const CREATE_LINEJOB_SUCCESS = 'CREATE_LINEJOB_SUCCESS';
export const CREATE_LINEJOB_ERROR = 'CREATE_LINEJOB_ERROR';

export const GET_LINE_STATIONS = 'GET_LINE_STATIONS';
export const GET_LINE_STATIONS_SUCCESS = 'GET_LINE_STATIONS_SUCCESS';
export const GET_LINE_STATIONS_ERROR = 'GET_LINE_STATIONS_ERROR';

export const GET_LINEJOB_STATIONS = 'GET_LINEJOB_STATIONS';
export const GET_LINEJOB_STATIONS_SUCCESS = 'GET_LINEJOB_STATIONS_SUCCESS';
export const GET_LINEJOB_STATIONS_ERROR = 'GET_LINEJOB_STATIONS_ERROR';

export const GET_LINEJOB_STATIONS_WITH_DETAILS = 'GET_LINEJOB_STATIONS_WITH_DETAILS';
export const GET_LINEJOB_STATIONS_WITH_DETAILS_SUCCESS = 'GET_LINEJOB_STATIONS_WITH_DETAILS_SUCCESS';
export const GET_LINEJOB_STATIONS_WITH_DETAILS_ERROR = 'GET_LINEJOB_STATIONS_WITH_DETAILS_ERROR';

export const SAVE_LINEJOB_STATIONS = 'SAVE_LINEJOB_STATIONS';
export const SAVE_LINEJOB_STATIONS_SUCCESS = 'SAVE_LINEJOB_STATIONS_SUCCESS';
export const SAVE_LINEJOB_STATIONS_ERROR = 'SAVE_LINEJOB_STATIONS_ERROR';

export const DELETE_LINEJOB_STATIONS = 'DELETE_LINEJOB_STATIONS';
export const DELETE_LINEJOB_STATIONS_SUCCESS = 'DELETE_LINEJOB_STATIONS_SUCCESS';
export const DELETE_LINEJOB_STATIONS_ERROR = 'DELETE_LINEJOB_STATIONS_ERROR';

export const GET_STATION_DOCUMENTS = 'GET_STATION_DOCUMENTS';
export const GET_STATION_DOCUMENTS_SUCCESS = 'GET_STATION_DOCUMENTS_SUCCESS';
export const GET_STATION_DOCUMENTS_ERROR = 'GET_STATION_DOCUMENTS_ERROR';

export const GET_STATION_DRAWINGS = 'GET_STATION_DRAWINGS';
export const GET_STATION_DRAWINGS_SUCCESS = 'GET_STATION_DRAWINGS_SUCCESS';
export const GET_STATION_DRAWINGS_ERROR = 'GET_STATION_DRAWINGS_ERROR';
export const STATION_DRAWINGS_PREUPLOAD = 'STATION_DRAWINGS_PREUPLOAD';
export const STATION_DRAWINGS_PREUPLOAD_SUCCESS = 'STATION_DRAWINGS_PREUPLOAD_SUCCESS';
export const STATION_DRAWINGS_PREUPLOAD_ERROR = 'STATION_DRAWINGS_PREUPLOAD_ERROR';
export const STATION_DRAWINGS_SAVE_FILE = 'STATION_DRAWINGS_SAVE_FILE';
export const STATION_DRAWINGS_SAVE_FILE_SUCCESS = 'STATION_DRAWINGS_SAVE_FILE_SUCCESS';
export const STATION_DRAWINGS_SAVE_FILE_ERROR = 'STATION_DRAWINGS_SAVE_FILE_ERROR';
export const CLEAR_STATION_DRAWINGS = 'CLEAR_STATION_DRAWINGS';

export const GET_OPERATOR_TASKS = 'GET_OPERATOR_TASKS';
export const GET_OPERATOR_TASKS_SUCCESS = 'GET_OPERATOR_TASKS_SUCCESS';
export const GET_OPERATOR_TASKS_ERROR = 'GET_OPERATOR_TASKS_ERROR';

export const GET_STATION_DETAILS = 'GET_STATION_DETAILS';
export const GET_STATION_DETAILS_SUCCESS = 'GET_STATION_DETAILS_SUCCESS';
export const GET_STATION_DETAILS_ERROR = 'GET_STATION_DETAILS_ERROR';
export const SET_STATION_DETAILS = 'SET_STATION_DETAILS';


export const GET_LINEJOBSTATION_KPI = 'GET_LINEJOBSTATION_KPI';
export const GET_LINEJOBSTATION_KPI_SUCCESS = 'GET_LINEJOBSTATION_KPI_SUCCESS';
export const GET_LINEJOBSTATION_KPI_ERROR = 'GET_LINEJOBSTATION_KPI_ERROR';

export const GET_OPERATOR_DRAWINGS = 'GET_OPERATOR_DRAWINGS';
export const GET_OPERATOR_DRAWINGS_SUCCESS = 'GET_OPERATOR_DRAWINGS_SUCCESS';
export const GET_OPERATOR_DRAWINGS_ERROR = 'GET_OPERATOR_DRAWINGS_ERROR';
export const SHOW_OPERATOR_DRAWINGS_ANNOTATIONS = 'SHOW_OPERATOR_DRAWINGS_ANNOTATIONS';

export const ADD_DOCUMENTS_TO_STATION = 'ADD_DOCUMENTS_TO_STATION';
export const REMOVE_DOCUMENTS_FROM_STATION = 'REMOVE_DOCUMENTS_FROM_STATION';

export const ADD_DRAWINGS_TO_STATION = 'ADD_DRAWINGS_TO_STATION';
export const REMOVE_DRAWINGS_FROM_STATION = 'REMOVE_DRAWINGS_FROM_STATION';

export const UPDATE_STATION_DOCUMENTS = 'UPDATE_STATION_DOCUMENTS';
export const UPDATE_STATION_DRAWINGS = 'UPDATE_STATION_DRAWINGS';
export const SAVE_NOTES = 'SAVE_NOTES';
export const SAVE_NOTES_SUCCESS = 'SAVE_NOTES_SUCCESS';
export const SAVE_NOTES_ERROR = 'SAVE_NOTES_ERROR';

export const SAVE_SUPERVISOR_DRAWINGS = 'SAVE_SUPERVISOR_DRAWINGS';
export const SAVE_SUPERVISOR_DRAWINGS_SUCCESS = 'SAVE_SUPERVISOR_DRAWINGS_SUCCESS';
export const SAVE_SUPERVISOR_DRAWINGS_ERROR = 'SAVE_SUPERVISOR_DRAWINGS_ERROR';

export const GET_LINEJOBSTATION_ID = 'GET_LINEJOBSTATION_ID';
export const SET_DRAWINGS_TO_LINEJOBSTATION = 'SET_DRAWINGS_TO_LINEJOBSTATION';
export const SET_LINEJOBSTATION_TASKS = 'SET_LINEJOBSTATION_TASKS';

export const CLEAR_LINEJOB_STATIONS_DATA = 'CLEAR_LINEJOB_STATIONS_DATA';

export const ADD_TASKS_TO_STATION = 'ADD_TASKS_TO_STATION';
export const REMOVE_TASKS_FROM_STATION = 'REMOVE_TASKS_FROM_STATION';

export const GET_LINEJOB_TASKS = 'GET_LINEJOB_TASKS';
export const GET_LINEJOB_TASKS_SUCCESS = 'GET_LINEJOB_TASKS_SUCCESS';
export const GET_LINEJOB_TASKS_ERROR = 'GET_LINEJOB_TASKS_ERROR';

export const GET_STATION_TASKS = 'GET_STATION_TASKS';
export const GET_STATION_TASKS_SUCCESS = 'GET_STATION_TASKS_SUCCESS';
export const GET_STATION_TASKS_ERROR = 'GET_STATION_TASKS_ERROR';

export const CREATE_NEW_TASK = 'CREATE_NEW_TASK';
export const CREATE_NEW_TASK_SUCCESS = 'CREATE_NEW_TASK_SUCCESS';
export const CREATE_NEW_TASK_ERROR = 'CREATE_NEW_TASK_ERROR';

export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR';

export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';

export const UPDATE_LINEJOB_STATION_TASKS = 'UPDATE_LINEJOB_STATION_TASKS';
export const CLEAR_LINEJOB_STATIONS_WIDGETS_DATA = 'CLEAR_LINEJOB_STATIONS_WIDGETS_DATA';
export const UPDATE_LINE_TASKS = 'UPDATE_LINE_TASKS';

export const CLEAR_LINEJOB_TASKS = 'CLEAR_LINEJOB_TASKS';

export const GET_CHOOSED_LINEJOB_BOMS = 'GET_CHOOSED_LINEJOB_BOMS';
export const GET_CHOOSED_LINEJOB_BOMS_SUCCESS = 'GET_CHOOSED_LINEJOB_BOMS_SUCCESS';
export const GET_CHOOSED_LINEJOB_BOMS_ERROR = 'GET_CHOOSED_LINEJOB_BOMS_ERROR';

export const GET_STATION_BOMS = 'GET_STATION_BOMS';
export const GET_STATION_BOMS_SUCCESS = 'GET_STATION_BOMS_SUCCESS';
export const GET_STATION_BOMS_ERROR = 'GET_STATION_BOMS_ERROR';

export const GET_LINEJOB_ITPS = 'GET_LINEJOB_ITPS';
export const GET_LINEJOB_ITPS_SUCCESS = 'GET_LINEJOB_ITPS_SUCCESS';
export const GET_LINEJOB_ITPS_ERROR = 'GET_LINEJOB_ITPS_ERROR';

export const GET_EXTERNAL_VDRS = 'GET_EXTERNAL_VDRS';
export const GET_EXTERNAL_VDRS_SUCCESS = 'GET_EXTERNAL_VDRS_SUCCESS';
export const GET_EXTERNAL_VDRS_ERROR = 'GET_EXTERNAL_VDRS_ERROR';

export const GET_EXTERNAL_ITPS = 'GET_EXTERNAL_ITPS';
export const GET_EXTERNAL_ITPS_SUCCESS = 'GET_EXTERNAL_ITPS_SUCCESS';
export const GET_EXTERNAL_ITPS_ERROR = 'GET_EXTERNAL_ITPS_ERROR';

export const GET_LINE_UNIT_CHECKS = 'GET_LINE_UNIT_CHECKS';
export const GET_LINE_UNIT_CHECKS_SUCCESS = 'GET_LINE_UNIT_CHECKS_SUCCESS';
export const GET_LINE_UNIT_CHECKS_ERROR = 'GET_LINE_UNIT_CHECKS_ERROR';

export const GET_STATION_UNIT_CHECKS = 'GET_STATION_UNIT_CHECKS';
export const GET_STATION_UNIT_CHECKS_SUCCESS = 'GET_STATION_UNIT_CHECKS_SUCCESS';
export const GET_STATION_UNIT_CHECKS_ERROR = 'GET_STATION_UNIT_CHECKS_ERROR';

export const DELETE_UNIT_CHECK = 'DELETE_UNIT_CHECK';
export const DELETE_UNIT_CHECK_SUCCESS = 'DELETE_UNIT_CHECK_SUCCESS';
export const DELETE_UNIT_CHECK_ERROR = 'DELETE_UNIT_CHECK_ERROR';

export const UPDATE_UNIT_CHECK = 'UPDATE_UNIT_CHECK';
export const UPDATE_UNIT_CHECK_SUCCESS = 'UPDATE_UNIT_CHECK_SUCCESS';
export const UPDATE_UNIT_CHECK_ERROR = 'UPDATE_UNIT_CHECK_ERROR';

export const ADD_NEW_UNIT_CHECK = 'ADD_NEW_UNIT_CHECK';
export const ADD_NEW_UNIT_CHECK_SUCCESS = 'ADD_NEW_UNIT_CHECK_SUCCESS';
export const ADD_NEW_UNIT_CHECK_ERROR = 'ADD_NEW_UNIT_CHECK_ERROR';

export const GET_STATION_UNIT_CHECKS_WITHOUT_SETTING_TO_REDUX = 'GET_STATION_UNIT_CHECKS_WITHOUT_SETTING_TO_REDUX';
export const GET_STATION_UNIT_CHECKS_WITHOUT_SETTING_TO_REDUX_SUCCESS = 'GET_STATION_UNIT_CHECKS_WITHOUT_SETTING_TO_REDUX_SUCCESS';
export const GET_STATION_UNIT_CHECKS_WITHOUT_SETTING_TO_REDUX_ERROR = 'GET_STATION_UNIT_CHECKS_WITHOUT_SETTING_TO_REDUX_ERROR';

export const SET_IS_HAS_STATION_UNIT_CHECKS = 'SET_IS_HAS_STATION_UNIT_CHECKS';
export const ADD_UNIT_CHECK_TO_STATION = 'ADD_UNIT_CHECK_TO_STATION';
export const UPDATE_WIDGET_UNIT_CHECKS = 'UPDATE_WIDGET_UNIT_CHECKS';
export const CLEAR_UNIT_CHECKS = 'CLEAR_UNIT_CHECKS';

export const UPDATE_SUPERVISOR_BOMS = 'UPDATE_SUPERVISOR_BOMS';
export const ADD_BOMS_TO_STATION = 'ADD_BOMS_TO_STATION';
export const SET_BOMS_TO_STATION = 'SET_BOMS_TO_STATION';
export const CLEAR_ADDED_STATION_BOMS = 'CLEAR_ADDED_STATION_BOMS';
export const SET_INITIAL_STATION_BOMS = 'SET_INITIAL_STATION_BOMS';
export const UPDATE_STATION_TASKS = 'UPDATE_STATION_TASKS';
export const CLEAR_STATION_BOMS = 'CLEAR_STATION_BOMS';

export const SAVE_MODIFIED_PDF = 'SAVE_MODIFIED_PDF';
export const UPDATING_PDF = 'UPDATING_PDF';
export const CLEAR_ADDED_STATION_TASKS = 'CLEAR_ADDED_STATION_TASKS';

export const GET_LINEJOB_VDRS = 'GET_LINEJOB_VDRS';
export const GET_LINEJOB_VDRS_SUCCESS = 'GET_LINEJOB_VDRS_SUCCESS';
export const GET_LINEJOB_VDRS_ERROR = 'GET_LINEJOB_VDRS_ERROR';

export const GET_STATION_VDRS = 'GET_STATION_VDRS';
export const GET_STATION_VDRS_SUCCESS = 'GET_STATION_VDRS_SUCCESS';
export const GET_STATION_VDRS_ERROR = 'GET_STATION_VDRS_ERROR';

export const SET_IS_HAS_STATION_VDRS = 'SET_IS_HAS_STATION_VDRS';
export const ADD_VDR_TO_STATION = 'ADD_VDR_TO_STATION';
export const UPDATE_WIDGET_VDRS = 'UPDATE_WIDGET_VDRS';
export const CLEAR_VDRS = 'CLEAR_VDRS';

export const GET_STATION_VDRS_WITHOUT_SETTING_TO_REDUX = 'GET_STATION_VDRS_WITHOUT_SETTING_TO_REDUX';
export const GET_STATION_VDRS_WITHOUT_SETTING_TO_REDUX_SUCCESS = 'GET_STATION_VDRS_WITHOUT_SETTING_TO_REDUX_SUCCESS';
export const GET_STATION_VDRS_WITHOUT_SETTING_TO_REDUX_ERROR = 'GET_STATION_VDRS_WITHOUT_SETTING_TO_REDUX_ERROR';


export const GET_SUPERVISOR_LINEJOB_ITPS = 'GET_SUPERVISOR_LINEJOB_ITPS';
export const GET_SUPERVISOR_LINEJOB_ITPS_SUCCESS = 'GET_SUPERVISOR_LINEJOB_ITPS_SUCCESS';
export const GET_SUPERVISOR_LINEJOB_ITPS_ERROR = 'GET_SUPERVISOR_LINEJOB_ITPS_ERROR';

export const GET_STATION_ITPS = 'GET_STATION_ITPS';
export const GET_STATION_ITPS_SUCCESS = 'GET_STATION_ITPS_SUCCESS';
export const GET_STATION_ITPS_ERROR = 'GET_STATION_ITPS_ERROR';

export const SET_IS_HAS_STATION_ITPS = 'SET_IS_HAS_STATION_ITPS';
export const ADD_ITP_TO_STATION = 'ADD_ITP_TO_STATION';
export const UPDATE_WIDGET_ITPS = 'UPDATE_WIDGET_ITPS';
export const CLEAR_ITPS = 'CLEAR_ITPS';

export const GET_STATION_ITPS_WITHOUT_SETTING_TO_REDUX = 'GET_STATION_ITPS_WITHOUT_SETTING_TO_REDUX';
export const GET_STATION_ITPS_WITHOUT_SETTING_TO_REDUX_SUCCESS = 'GET_STATION_ITPS_WITHOUT_SETTING_TO_REDUX_SUCCESS';
export const GET_STATION_ITPS_WITHOUT_SETTING_TO_REDUX_ERROR = 'GET_STATION_ITPS_WITHOUT_SETTING_TO_REDUX_ERROR';

export const GET_ACTIVE_LINE_JOBS = 'GET_ACTIVE_LINE_JOBS';
export const GET_ACTIVE_LINE_JOBS_SUCCESS = 'GET_ACTIVE_LINE_JOBS_SUCCESS';
export const GET_ACTIVE_LINE_JOBS_ERROR = 'GET_ACTIVE_LINE_JOBS_ERROR';

export const GET_LINE_WORK_ORDER_HOURS = 'GET_LINE_WORK_ORDER_HOURS';
export const GET_LINE_WORK_ORDER_HOURS_SUCCESS = 'GET_LINE_WORK_ORDER_HOURS_SUCCESS';
export const GET_LINE_WORK_ORDER_HOURS_ERROR = 'GET_LINE_WORK_ORDER_HOURS_ERROR';

export const GET_LINE_MONTHLY_SHIFT_GOALS = 'GET_LINE_MONTHLY_SHIFT_GOALS';
export const GET_LINE_MONTHLY_SHIFT_GOALS_SUCCESS = 'GET_LINE_MONTHLY_SHIFT_GOALS_SUCCESS';
export const GET_LINE_MONTHLY_SHIFT_GOALS_ERROR = 'GET_LINE_MONTHLY_SHIFT_GOALS_ERROR';

export const SET_PLANNED_SHIFT = 'SET_PLANNED_SHIFT';
export const SET_PLANNED_SHIFT_SUCCESS = 'SET_PLANNED_SHIFT_SUCCESS';
export const SET_PLANNED_SHIFT_ERROR = 'SET_PLANNED_SHIFT_ERROR';

export const GET_LINE_AVERAGES = 'GET_LINE_AVERAGES';
export const GET_LINE_AVERAGES_SUCCESS = 'GET_LINE_AVERAGES_SUCCESS';
export const GET_LINE_AVERAGES_ERROR = 'GET_LINE_AVERAGES_ERROR';

export const GET_ACTIVE_LINE_JOBS_STATIONS = 'GET_ACTIVE_LINE_JOBS_STATIONS';
export const GET_ACTIVE_LINE_JOBS_STATIONS_SUCCESS = 'GET_ACTIVE_LINE_JOBS_STATIONS_SUCCESS';
export const GET_ACTIVE_LINE_JOBS_STATIONS_ERROR = 'GET_ACTIVE_LINE_JOBS_STATIONS_ERROR';

export const GET_OPENED_STATION_TASKS = 'GET_OPENED_STATION_TASKS';
export const GET_OPENED_STATION_TASKS_SUCCESS = 'GET_OPENED_STATION_TASKS_SUCCESS';
export const GET_OPENED_STATION_TASKS_ERROR = 'GET_OPENED_STATION_TASKS_ERROR';

export const CLEAR_OPENED_STATION_TASKS = 'CLEAR_OPENED_STATION_TASKS';

export const UPDATE_MODIFIED_DRAWINGS_FILES = 'UPDATE_MODIFIED_DRAWINGS_FILES';

export const GET_TEMPLATES = 'GET_TEMPLATES';
export const GET_TEMPLATES_SUCCESS = 'GET_TEMPLATES_SUCCESS';
export const GET_TEMPLATES_ERROR = 'GET_TEMPLATES_ERROR';

export const CREATE_TEMPLATE = 'GET_TEMPLATES';
export const CREATE_TEMPLATE_SUCCESS = 'GET_TEMPLATES_SUCCESS';
export const CREATE_TEMPLATE_ERROR = 'GET_TEMPLATES_ERROR';

export const APPLY_TEMPLATE = 'APPLY_TEMPLATE';
export const APPLY_TEMPLATE_SUCCESS = 'APPLY_TEMPLATE_SUCCESS';
export const APPLY_TEMPLATE_ERROR = 'APPLY_TEMPLATE_ERROR';

export const DELETE_TEMPLATE = 'APPLY_TEMPLATE';
export const DELETE_TEMPLATE_SUCCESS = 'APPLY_TEMPLATE_SUCCESS';
export const DELETE_TEMPLATE_ERROR = 'APPLY_TEMPLATE_ERROR';

export const GET_OPERATOR_SIDEBAR_DATA = 'GET_OPERATOR_SIDEBAR_DATA';
export const GET_OPERATOR_SIDEBAR_DATA_SUCCESS = 'GET_OPERATOR_SIDEBAR_DATA_SUCCESS';
export const GET_OPERATOR_SIDEBAR_DATA_ERROR = 'GET_OPERATOR_SIDEBAR_DATA_ERROR';

export const GET_LINEJOB_NOTES_OPERATOR_VIEW = 'GET_LINEJOB_NOTES_OPERATOR_VIEW';
export const GET_LINEJOB_NOTES_OPERATOR_VIEW_SUCCESS = 'GET_LINEJOB_NOTES_OPERATOR_VIEW_SUCCESS';
export const GET_LINEJOB_NOTES_OPERATOR_VIEW_ERROR = 'GET_LINEJOB_NOTES_OPERATOR_VIEW_ERROR';

export const GET_OPERATOR_STATION_DOCUMENTS = 'GET_OPERATOR_STATION_DOCUMENTS';
export const GET_OPERATOR_STATION_DOCUMENTS_SUCCESS = 'GET_OPERATOR_STATION_DOCUMENTS_SUCCESS';
export const GET_OPERATOR_STATION_DOCUMENTS_ERROR = 'GET_OPERATOR_STATION_DOCUMENTS_ERROR';

export const LAST_OPENED_DRAWING = 'LAST_OPENED_DRAWING';

export const GET_OPERATOR_UNIT_CHECKS = 'GET_OPERATOR_UNIT_CHECKS';
export const GET_OPERATOR_UNIT_CHECKS_SUCCESS = 'GET_OPERATOR_UNIT_CHECKS_SUCCESS';
export const GET_OPERATOR_UNIT_CHECKS_ERROR = 'GET_OPERATOR_UNIT_CHECKS_ERROR';

export const APPROVE_FIRST_ARTICLE = 'APPROVE_FIRST_ARTICLE';
export const APPROVE_FIRST_ARTICLE_SUCCESS = 'APPROVE_FIRST_ARTICLE_SUCCESS';
export const APPROVE_FIRST_ARTICLE_ERROR = 'APPROVE_FIRST_ARTICLE_ERROR';

export const START_UNIT_CHECK = 'START_UNIT_CHECK';
export const START_UNIT_CHECK_SUCCESS = 'START_UNIT_CHECK_SUCCESS';
export const START_UNIT_CHECK_ERROR = 'START_UNIT_CHECK_ERROR';

export const FINISH_UNIT_CHECK = 'FINISH_UNIT_CHECK';
export const FINISH_UNIT_CHECK_SUCCESS = 'FINISH_UNIT_CHECK_SUCCESS';
export const FINISH_UNIT_CHECK_ERROR = 'FINISH_UNIT_CHECK_ERROR';

export const DONE_UNIT_CHECK = 'DONE_UNIT_CHECK';
export const DONE_UNIT_CHECK_SUCCESS = 'DONE_UNIT_CHECK_SUCCESS';
export const DONE_UNIT_CHECK_ERROR = 'DONE_UNIT_CHECK_ERROR';

export const UNDONE_UNIT_CHECK = 'UNDONE_UNIT_CHECK';
export const UNDONE_UNIT_CHECK_SUCCESS = 'UNDONE_UNIT_CHECK_SUCCESS';
export const UNDONE_UNIT_CHECK_ERROR = 'UNDONE_UNIT_CHECK_ERROR';

export const GET_LOGS = 'GET_LOGS';
export const GET_LOGS_SUCCESS = 'GET_LOGS_SUCCESS';
export const GET_LOGS_ERROR = 'GET_LOGS_ERROR';

export const GET_OPERATOR_STATION_BOMS = 'GET_OPERATOR_STATION_BOMS';
export const GET_OPERATOR_STATION_BOMS_SUCCESS = 'GET_OPERATOR_STATION_BOMS_SUCCESS';
export const GET_OPERATOR_STATION_BOMS_ERROR = 'GET_OPERATOR_STATION_BOMS_ERROR';

export const GET_SIGNAL_TYPES = 'GET_SIGNAL_TYPES';
export const GET_SIGNAL_TYPES_SUCCESS = 'GET_SIGNAL_TYPES_SUCCESS';
export const GET_SIGNAL_TYPES_ERROR = 'GET_SIGNAL_TYPES_ERROR';

export const GET_URGENCY_SIGNAL_TYPES = 'GET_URGENCY_SIGNAL_TYPES';
export const GET_URGENCY_SIGNAL_TYPES_SUCCESS = 'GET_URGENCY_SIGNAL_TYPES_SUCCESS';
export const GET_URGENCY_SIGNAL_TYPES_ERROR = 'GET_URGENCY_SIGNAL_TYPES_ERROR';

export const GET_SIGNALS_FOR_LINEJOBSTATION_TYPES = 'GET_SIGNALS_FOR_LINEJOBSTATION_TYPES';
export const GET_SIGNALS_FOR_LINEJOBSTATION_SUCCESS = 'GET_SIGNALS_FOR_LINEJOBSTATION_SUCCESS';
export const GET_SIGNALS_FOR_LINEJOBSTATION_ERROR = 'GET_SIGNALS_FOR_LINEJOBSTATION_ERROR';

export const SEND_SIGNAL = 'SEND_SIGNAL';
export const SEND_SIGNAL_SUCCESS = 'SEND_SIGNAL_SUCCESS';
export const SEND_SIGNAL_ERROR = 'SEND_SIGNAL_ERROR';

export const CLEAR_ACTIVE_SIGNALS = 'CLEAR_ACTIVE_SIGNALS';
export const CLEAR_ACTIVE_SIGNALS_SUCCESS = 'CLEAR_ACTIVE_SIGNALS_SUCCESS';
export const CLEAR_ACTIVE_SIGNALS_ERROR = 'CLEAR_ACTIVE_SIGNALS_ERROR';

export const GET_MONITOR_STATIONS_SIGNALS = 'GET_MONITOR_STATIONS_SIGNALS';
export const GET_MONITOR_STATIONS_SIGNALS_SUCCESS = 'GET_MONITOR_STATIONS_SIGNALS_SUCCESS';
export const GET_MONITOR_STATIONS_SIGNALS_ERROR = 'GET_MONITOR_STATIONS_SIGNALS_ERROR';

export const MARK_SIGNAL_AS_VIEWED = 'MARK_SIGNAL_AS_VIEWED';
export const MARK_SIGNAL_AS_VIEWED_SUCCESS = 'MARK_SIGNAL_AS_VIEWED_SUCCESS';
export const MARK_SIGNAL_AS_VIEWED_ERROR = 'MARK_SIGNAL_AS_VIEWED_ERROR';

export const SET_OPERATOR_SIGNALS = 'SET_OPERATOR_SIGNALS';
export const UPDATE_OPERATOR_SIGNALS = 'UPDATE_OPERATOR_SIGNALS';
export const RESET_SIGNALS = 'RESET_SIGNALS';

export const CLEAR_OPERATOR_DATA = 'CLEAR_OPERATOR_DATA';

export const GET_LINEJOB_REVISION_NOTIFICATION = 'GET_LINEJOB_REVISION_NOTIFICATION';
export const GET_LINEJOB_REVISION_NOTIFICATION_SUCCESS = 'GET_LINEJOB_REVISION_NOTIFICATION_SUCCESS';
export const GET_LINEJOB_REVISION_NOTIFICATION_ERROR = 'GET_LINEJOB_REVISION_NOTIFICATION_ERROR';

export const GET_LAST_REVISIONS = 'GET_LAST_REVISIONS';
export const GET_LAST_REVISIONS_SUCCESS = 'GET_LAST_REVISIONS_SUCCESS';
export const GET_LAST_REVISIONS_ERROR = 'GET_LAST_REVISIONS_ERROR';

export const MARK_NOTIFICATION_AS_READ_OPERATOR = 'MARK_NOTIFICATION_AS_READ_OPERATOR';
export const MARK_NOTIFICATION_AS_READ_OPERATOR_SUCCESS = 'MARK_NOTIFICATION_AS_READ_OPERATOR_SUCCESS';
export const MARK_NOTIFICATION_AS_READ_OPERATOR_ERROR = 'MARK_NOTIFICATION_AS_READ_OPERATOR_ERROR';

export const MARK_NOTIFICATION_AS_READ_SUPERVISOR = 'MARK_NOTIFICATION_AS_READ_SUPERVISOR';
export const MARK_NOTIFICATION_AS_READ_SUPERVISOR_SUCCESS = 'MARK_NOTIFICATION_AS_READ_SUPERVISOR_SUCCESS';
export const MARK_NOTIFICATION_AS_READ_SUPERVISOR_ERROR = 'MARK_NOTIFICATION_AS_READ_SUPERVISOR_ERROR';

export const VIEW_NOTIFICATIONS_MODAL = 'VIEW_NOTIFICATIONS_MODAL';
export const VIEW_NOTIFICATIONS_MODAL_SUCCESS = 'VIEW_NOTIFICATIONS_MODAL_SUCCESS';
export const VIEW_NOTIFICATIONS_MODAL_ERROR = 'VIEW_NOTIFICATIONS_MODAL_ERROR';

export const VIEW_NOTIFICATIONS_MODAL_AS_OPERATOR = 'VIEW_NOTIFICATIONS_MODAL';
export const VIEW_NOTIFICATIONS_MODAL_AS_OPERATOR_SUCCESS = 'VIEW_NOTIFICATIONS_MODAL_SUCCESS';
export const VIEW_NOTIFICATIONS_MODAL_AS_OPERATOR_ERROR = 'VIEW_NOTIFICATIONS_MODAL_ERROR';

export const SEND_ISSUE_REVISION = 'SEND_ISSUE_REVISION';
export const SEND_ISSUE_REVISION_SUCCESS = 'SEND_ISSUE_REVISION_SUCCESS';
export const SEND_ISSUE_REVISION_ERROR = 'SEND_ISSUE_REVISION_ERROR';

export const GET_STATION_REVISED_ELEMENT_TYPE = 'GET_STATION_REVISED_ELEMENT_TYPE';
export const GET_STATION_REVISED_ELEMENT_TYPE_SUCCESS = 'GET_STATION_REVISED_ELEMENT_TYPE_SUCCESS';
export const GET_STATION_REVISED_ELEMENT_TYPE_ERROR = 'GET_STATION_REVISED_ELEMENT_TYPE_ERROR';

export const GET_LINEJOB_REVISED_ELEMENT_TYPES = 'GET_LINEJOB_REVISED_ELEMENT_TYPES';
export const GET_LINEJOB_REVISED_ELEMENT_TYPES_SUCCESS = 'GET_LINEJOB_REVISED_ELEMENT_TYPES_SUCCESS';
export const GET_LINEJOB_REVISED_ELEMENT_TYPES_ERROR = 'GET_LINEJOB_REVISED_ELEMENT_TYPES_ERROR';

export const UPDATE_STATION_NOTIFICATIONS_LIST = 'UPDATE_STATION_NOTIFICATIONS_LIST';
export const UPDATE_SUPERVISOR_NOTIFICATIONS_LIST = 'UPDATE_SUPERVISOR_NOTIFICATIONS_LIST';

export const CLEAR_REVISION_NOTIFICATIONS = 'CLEAR_REVISION_NOTIFICATIONS';
export const CLEAR_REVISION_NOTIFICATION_DATE = 'CLEAR_REVISION_NOTIFICATION_DATE';
export const CLEAR_MONITOR_REVISION_NOTIFICATIONS = 'CLEAR_MONITOR_REVISION_NOTIFICATIONS';
export const SET_LINEJOB_STATION_DELETED_NOTIFICATION = 'SET_LINEJOB_STATION_DELETED_NOTIFICATION';

export const GET_STATIONS_NOTIFICATIONS = 'GET_STATIONS_NOTIFICATIONS';
export const GET_STATIONS_NOTIFICATIONS_SUCCESS = 'GET_STATIONS_NOTIFICATIONS_SUCCESS';
export const GET_STATIONS_NOTIFICATIONS_ERROR = 'GET_STATIONS_NOTIFICATIONS_ERROR';

export const GET_OPERATOR_REVISION_NOTIFICATION = 'GET_OPERATOR_REVISION_NOTIFICATION';
export const GET_OPERATOR_REVISION_NOTIFICATION_SUCCESS = 'GET_OPERATOR_REVISION_NOTIFICATION_SUCCESS';
export const GET_OPERATOR_REVISION_NOTIFICATION_ERROR = 'GET_OPERATOR_REVISION_NOTIFICATION_ERROR';

export const GET_SUPERVISOR_REVISION_NOTIFICATION = 'GET_SUPERVISOR_REVISION_NOTIFICATION';
export const GET_SUPERVISOR_REVISION_NOTIFICATION_SUCCESS = 'GET_SUPERVISOR_REVISION_NOTIFICATION_SUCCESS';
export const GET_SUPERVISOR_REVISION_NOTIFICATION_ERROR = 'GET_SUPERVISOR_REVISION_NOTIFICATION_ERROR';

export const GET_RECENT_FILES = 'GET_RECENT_FILES';
export const GET_RECENT_FILES_SUCCESS = 'GET_RECENT_FILES_SUCCESS';
export const GET_RECENT_FILES_ERROR = 'GET_RECENT_FILES_ERROR';

export const GET_FILE_DATA = 'GET_FILE_DATA';
export const GET_FILE_DATA_SUCCESS = 'GET_FILE_DATA_SUCCESS';
export const GET_FILE_DATA_ERROR = 'GET_FILE_DATA_ERROR';

export const SAVE_RECENT_FILES_DRAWINGS = 'SAVE_RECENT_FILES_DRAWINGS';

export const SAVE_RECENT_FILES_DOCUMENTS = 'SAVE_RECENT_FILES_DOCUMENTS';

export const CLEAR_RECENT_FILES_DATA = 'CLEAR_RECENT_FILES_DATA';

export const CHECK_SAME_FILE = 'CHECK_SAME_FILE';
export const CHECK_DRAWING_VERSION = 'CHECK_DRAWING_VERSION';
export const IS_NEED_TO_ADD_ANNOTATION = 'IS_NEED_TO_ADD_ANNOTATION';
export const SET_IS_PREV_FILE_HAS_ANNOTATION = 'SET_IS_PREV_FILE_HAS_ANNOTATION';
export const OPEN_RECENT_FILES_LOADER = 'OPEN_RECENT_FILES_LOADER';

export const OPERATOR_AUTH = 'OPERATOR_AUTH';
export const OPERATOR_AUTH_SUCCESS = 'OPERATOR_AUTH_SUCCESS';
export const OPERATOR_AUTH_ERROR = 'OPERATOR_AUTH_ERROR';

export const GET_USER_AUTH_ROLES = 'GET_USER_AUTH_ROLES';
export const GET_USER_AUTH_ROLES_SUCCESS = 'GET_USER_AUTH_ROLES_SUCCESS';
export const GET_USER_AUTH_ROLES_ERROR = 'GET_USER_AUTH_ROLES_ERROR';

export const CHANGE_VIEW = 'CHANGE_VIEW';
